package ai

import model.{Message, Id}
import upickle.default._
import scala.util.Try

/**
 * A summary of multiple messages generated by an AI.
 * We want the AI to return this EXACT structure.
 */
case class BoardSummary(
  summary: String,
  totalMessages: Int,
  topics: List[String]
)
object BoardSummary {
  implicit val rw: ReadWriter[BoardSummary] = macroRW
}

trait AIService {
  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary]
}

/**
 * Real implementation using Google's Gemini API.
 */
class GeminiAIService(apiKey: String) extends AIService {
  private val model = "gemini-1.5-flash"
  private val url = s"https://generativelanguage.googleapis.com/v1beta/models/$model:generateContent?key=$apiKey"

  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary] = {
    if (messages.isEmpty) return Right(BoardSummary("No messages to summarize yet.", 0, Nil))

    val messagesText = messages.map(m => s"- ${m.content}").mkString("\n")
    val prompt =
      s"""Summarize the following message board posts and identify the main topics discussed.
         |Return the result ONLY as a JSON object matching this schema:
         |{
         |  "summary": "A brief 1-2 sentence summary",
         |  "totalMessages": ${messages.size},
         |  "topics": ["topic1", "topic2"]
         |}
         |
         |Messages:
         |$messagesText
         |""".stripMargin

    val payload = ujson.Obj(
      "contents" -> ujson.Arr(
        ujson.Obj(
          "parts" -> ujson.Arr(
            ujson.Obj("text" -> prompt)
          )
        )
      )
    )

    Try {
      val resp = requests.post(
        url,
        data = payload.render(),
        headers = Map("Content-Type" -> "application/json")
      )
      
      val json = ujson.read(resp.text())
      // Gemini response structure: candidates[0].content.parts[0].text
      val aiText = json("candidates")(0)("content")("parts")(0)("text").str
      SchemaValidator.validate[BoardSummary](aiText)
    }.toEither.left.map(_.getMessage).flatten
  }
}

/**
 * A mock implementation for now (to avoid needing an API key immediately).
 * This will show how the validation works.
 */
object MockAIService extends AIService {
  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary] = {
    // This is what an LLM might return
    val rawJson = s"""
      {
        "summary": "People are testing the new Scala ORM and AI features.",
        "totalMessages": ${messages.size},
        "topics": ["Scala", "ORM", "AI"]
      }
    """
    SchemaValidator.validate[BoardSummary](rawJson)
  }
}
