package ai

import model.{Message, Id}
import upickle.default._

/**
 * A summary of multiple messages generated by an AI.
 * We want the AI to return this EXACT structure.
 */
case class BoardSummary(
  summary: String,
  totalMessages: Int,
  topics: List[String]
)
object BoardSummary {
  implicit val rw: ReadWriter[BoardSummary] = macroRW
}

trait AIService {
  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary]
}

/**
 * A mock implementation for now (to avoid needing an API key immediately).
 * This will show how the validation works.
 */
object MockAIService extends AIService {
  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary] = {
    // This is what an LLM might return
    val rawJson = s"""
      {
        "summary": "People are testing the new Scala ORM and AI features.",
        "totalMessages": ${messages.size},
        "topics": ["Scala", "ORM", "AI"]
      }
    """
    SchemaValidator.validate[BoardSummary](rawJson)
  }
}
