package ai

import model.{Message, Id}
import upickle.default._
import scala.util.{Try, Success, Failure}

/**
 * A summary of multiple messages generated by an AI.
 * We want the AI to return this EXACT structure.
 */
case class BoardSummary(
  summary: String,
  totalMessages: Int,
  topics: List[String]
)
object BoardSummary {
  implicit val rw: ReadWriter[BoardSummary] = macroRW
}

trait AIService {
  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary]
}

/**
 * Real implementation using Google's Gemini API.
 */
class GeminiAIService(apiKey: String) extends AIService {
  private val model = "gemini-2.0-flash-lite"
  private val url = s"https://generativelanguage.googleapis.com/v1/models/$model:generateContent?key=$apiKey"

  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary] = {
    if (messages.isEmpty) return Right(BoardSummary("No messages to summarize yet.", 0, Nil))

    val messagesText = messages.map(m => s"- ${m.content}").mkString("\n")
    val prompt =
      s"""Summarize these messages. Return ONLY JSON:
         |{
         |  "summary": "...",
         |  "totalMessages": ${messages.size},
         |  "topics": ["topic1"]
         |}
         |Messages:
         |$messagesText
         |""".stripMargin

    val payload = ujson.Obj(
      "contents" -> ujson.Arr(
        ujson.Obj("parts" -> ujson.Arr(ujson.Obj("text" -> prompt)))
      )
    )

    Try {
      val resp = requests.post(
        url,
        data = payload.render(),
        headers = Map("Content-Type" -> "application/json"),
        check = false
      )
      
      if (resp.statusCode == 429) {
        throw new RuntimeException("Quota Exceeded (429). Please check your Google AI Studio billing/limits.")
      } else if (resp.statusCode != 200) {
        throw new RuntimeException(s"API Error ${resp.statusCode}: ${resp.text()}")
      }

      val json = ujson.read(resp.text())
      val aiText = json("candidates")(0)("content")("parts")(0)("text").str.trim
      SchemaValidator.validate[BoardSummary](aiText)
    } match {
      case Success(res) => res
      case Failure(ex) => 
        val msg = ex.getMessage
        Left(msg)
    }
  }
}

/**
 * Implementation using Groq's high-speed Llama 3 API.
 * Uses the OpenAI-compatible chat completion endpoint.
 */
class GroqAIService(apiKey: String) extends AIService {
  private val model = "llama-3.3-70b-versatile"
  private val url = "https://api.groq.com/openai/v1/chat/completions"

  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary] = {
    if (messages.isEmpty) return Right(BoardSummary("No messages to summarize yet.", 0, Nil))

    val messagesText = messages.map(m => s"- ${m.content}").mkString("\n")
    val prompt =
      s"""Summarize these messages. Return ONLY JSON:
         |{
         |  "summary": "...",
         |  "totalMessages": ${messages.size},
         |  "topics": ["topic1"]
         |}
         |Messages:
         |$messagesText
         |""".stripMargin

    val payload = ujson.Obj(
      "model" -> model,
      "messages" -> ujson.Arr(
        ujson.Obj("role" -> "user", "content" -> prompt)
      ),
      "response_format" -> ujson.Obj("type" -> "json_object")
    )

    Try {
      val resp = requests.post(
        url,
        data = payload.render(),
        headers = Map(
          "Content-Type" -> "application/json",
          "Authorization" -> s"Bearer $apiKey"
        ),
        check = false
      )
      
      if (resp.statusCode != 200) {
        throw new RuntimeException(s"Groq API Error ${resp.statusCode}: ${resp.text()}")
      }

      val json = ujson.read(resp.text())
      val aiText = json("choices")(0)("message")("content").str.trim
      SchemaValidator.validate[BoardSummary](aiText)
    } match {
      case Success(res) => res
      case Failure(ex) => 
        val msg = ex.getMessage
        Left(msg)
    }
  }
}

/**
 * Fallback mock implementation.
 */
object MockAIService extends AIService {
  def summarize(messages: Seq[Message[Id]]): Either[String, BoardSummary] = {
    Right(BoardSummary(
      "This is a MOCK summary. Plug in a Groq or Gemini key to see real AI.",
      messages.size,
      List("Mocking", "Test")
    ))
  }
}
